name: Prebuild
on:
  release:
    types: [published]
jobs:
  build_aarch64_linux:
    name: Prebuild aarch64 Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        node: [20, 22, 24]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install --build-from-source

      - name: Package prebuild
        run: |
          sudo apt update -y && sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ npx node-pre-gyp --target_arch=arm64 configure build package

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 'build/stage/**/*.tar.gz'

  build_aarch64_mac:
    name: Prebuild aarch64 macOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26]
        node: [20, 22, 24]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install --build-from-source

      - name: Package prebuild
        run: npm run build

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 'build/stage/**/*.tar.gz'

